### ISSUE TITLE
open and close tabitem

### ISSUE THREAD

**Issue by Janekkk333** [GavickPro/Tabs-GK5#24]
If I do not select the default tab in backend, so the frontend side shows only the inactive tabs menu. TabsItems are hide. When I click on any tab in this menu, it continues to open a tabs item content.
And now for what I need to know.
When I click a second time on the same tab in tabnav, I need that opened tabitem close again. This means that the appearance on the page will again only the inactive tabs menu.
Could you advise me on how to achieve this? Because currently it does not work. When I have had it opened tabsitem second click closes. Tabsitem is still open.

**Comment by dziudek** [comment]
Hello,

Please give me an example of your issue, because your description is totally not clear for me.
