### ISSUE TITLE
GK5 Tabs functioning correctly

### ISSUE THREAD

**Issue by concretemccann** [GavickPro/Tabs-GK5#27]
Hi All,

I have GK5 Tabs install on a website I now manage. I inherited it about 2 months ago and have been carrying out updates and fixes. The GK5 Tabs don't work when clicked on. The do work on the old version of the website which was running Joomla 2.5. Since the upgrade to Joomla 3.4.1 the tabs are not responsive. 

Can anyone shine any light on this problem or has anyone encountered the same, if so is there a fix?

Thanks,

Fergal

**Comment by dziudek** [comment]
Hello,

Please provide an URL to your website with this issue - without it we are unable to help you.

**Comment by concretemccann** [comment]
Hi dziudek,

the web address is http://www.fintonagaa.com. The site is in maintenance mode so the username and password are 'sneekpeek'.

Thanks,

Fergal

**Comment by dziudek** [comment]
Please try to remove the module override from your template (html/mod_tabs_gk5) - it seems that you have no gkTab CSS class in your structure - this class is necessary for the module scripts.

**Comment by concretemccann** [comment]
what do you mean override from the template?

**Comment by dziudek** [comment]
I mean that most probably in your template directory you have a html/mod_tabs_gk5/default.php file which contains old version of the Tabs GK5 module view without the gkTab CSS class.

**Comment by concretemccann** [comment]
Hi,

I removed the Tabs GK5 module and reinstalled it the module again but the same thing is happening.
Can you offer any further advice?

Thanks,

Fergal

**Comment by dziudek** [comment]
It is not related to your module, but to your template - so without removing/changing the template override for the module you won't be able to fix this issue.

**Comment by concretemccann** [comment]
Hey, I realised that after re-reading your previous post. All sorted now.

Cheers,

Fergal
